[Settings]
ID = "f10bab71-4897-404d-9779-ad37717845c1"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.

[build]
  publish = "dist"
  # This will be your default build command
  command = "npm run generate;echo \"User-Agent: *\nDisallow: /\" > /opt/build/repo/dist/robots.txt"

# Production context: All deploys from the Production branch set in your site's deploy settings will inherit these settings.
[context.production]
  #ドメイン登録したら開放する
  # command = "npm run generate;echo \"User-Agent: *\" > dist/robots.txt"
  # environment = { ACCESS_TOKEN = "super secret", NODE_ENV = "8.0.1" }

# Deploy Preview context: All Deploy Previews (https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/)
# will inherit these settings.


# Here is another way to define context specific environment variables
[context.deploy-preview.environment]
  # environment = { ACCESS_TOKEN = "super secret", NODE_ENV = "8.0.1" }

# Branch Deploy context: All deploys that are not resulting from a Pull/Merge Request and not from the primary, linked branch will inherit these settings.
[context.branch-deploy.environment]

[[headers]]
  # for = "/*" # This defines which paths this specific [[headers]] block will cover.
  # [headers.values]
  #   X-Frame-Options = "DENY"
  #   X-XSS-Protection = "1; mode=block"
  #   Content-Security-Policy = "frame-ancestors https://www.facebook.com"
  #   # Multi-key header rules are expressed with multi-line strings
  #   Link = '''
  #   </assets/css/base.css>; rel=preload; as=style, \
  #   </assets/css/base2.css>; rel=preload; as=style, \
  #   </assets/css/base3.css>; rel=preload; as=style'''
  #   # Basic-Auth allows you to password protect your whole site but is only available
  #   # to paid accounts
  #   Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"